name: Build and Deploy FE

on:
  push:
    branches:
      - main  # Pastikan ini nama branch utama lu

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4 # Update ke v4 biar up-to-date

      - name: Setup Node.js
        uses: actions/setup-node@v4 # Update ke v4
        with:
          node-version: '22' # Pakai Node 22 agar tidak kena warning deprecated

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: |
          CI=false npm run build # Ditambahkan CI=false agar build tidak gagal karena unused variable
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
          VITE_OFFICE_WHATSAPP: ${{ secrets.VITE_OFFICE_WHATSAPP }}
          VITE_PHONE_SANDI: ${{ secrets.VITE_PHONE_SANDI }}
          VITE_PHONE_FRADIYA: ${{ secrets.VITE_PHONE_FRADIYA }}
          VITE_PHONE_YUANITA: ${{ secrets.VITE_PHONE_YUANITA }}
          VITE_PHONE_DARUS: ${{ secrets.VITE_PHONE_DARUS }}

      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5 # Update ke versi paling stabil 4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/  
          server-dir: ./      
          port: 21
          protocol: ftp
          security: loose     # SANGAT PENTING: Supaya tidak gagal jabat tangan SSL/TLS dengan cPanel
          timeout: 90000      # Memperpanjang napas koneksi agar tidak cepat timeout